CREATE TABLE PERSONA(
    CEDULA BIGINT PRIMARY KEY NOT NULL,
    NOMBRE VARCHAR(255) NOT NULL,
    APELLIDO VARCHAR(255) NOT NULL,
    TELEFONO BIGINT NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    CONTRA VARCHAR(255) NOT NULL
);

CREATE TABLE USUARIO(
    ID BIGINT PRIMARY KEY NOT NULL,
    FOREIGN KEY (ID) REFERENCES PERSONA(CEDULA)
);

CREATE TABLE ADMIN(
    ID BIGINT PRIMARY KEY NOT NULL,
    FOREIGN KEY (ID) REFERENCES PERSONA(CEDULA)
);

CREATE TABLE repuestos ( id INT NOT NULL AUTO_INCREMENT , 
nombre VARCHAR(25) NOT NULL , marca VARCHAR(25) NOT NULL , 
precio INT NOT NULL , cantidad INT NOT NULL , descripcion VARCHAR(25) NOT NULL ,
imagen longblob,
 PRIMARY KEY (`id`)) ENGINE = InnoDB; 
